"""empty message

Revision ID: 1db6eac30acd
Revises: 45cd07995d61
Create Date: 2020-05-23 15:42:15.490354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db6eac30acd'
down_revision = '45cd07995d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Guess1', sa.String(length=255), nullable=True),
    sa.Column('Guess2', sa.String(length=255), nullable=True),
    sa.Column('Guess3', sa.String(length=255), nullable=True),
    sa.Column('Guess4', sa.String(length=255), nullable=True),
    sa.Column('Guess5', sa.String(length=255), nullable=True),
    sa.Column('Guess6', sa.String(length=255), nullable=True),
    sa.Column('Guess7', sa.String(length=255), nullable=True),
    sa.Column('Guess8', sa.String(length=255), nullable=True),
    sa.Column('Guess9', sa.String(length=255), nullable=True),
    sa.Column('Guess10', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guesses')
    # ### end Alembic commands ###
