"""empty message

Revision ID: 45cd07995d61
Revises: 
Create Date: 2020-05-23 15:29:50.129066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cd07995d61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Answer1', sa.String(length=255), nullable=True),
    sa.Column('Answer2', sa.String(length=255), nullable=True),
    sa.Column('Answer3', sa.String(length=255), nullable=True),
    sa.Column('Answer4', sa.String(length=255), nullable=True),
    sa.Column('Answer5', sa.String(length=255), nullable=True),
    sa.Column('Answer6', sa.String(length=255), nullable=True),
    sa.Column('Answer7', sa.String(length=255), nullable=True),
    sa.Column('Answer8', sa.String(length=255), nullable=True),
    sa.Column('Answer9', sa.String(length=255), nullable=True),
    sa.Column('Answer10', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    # ### end Alembic commands ###
